=== huangtingliu/lanting/WebRoot/WEB-INF/sysxml/mappers.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.weimingfj.com/xsd/mappers" xmlns="http://www.weimingfj.com/xsd/mappers"
	elementFormDefault="qualified">
	<xsd:element name="isNotEmpty">
		<xsd:annotation>
			<xsd:documentation>
					<![CDATA[
					判断节点，property不为空的时候该节点的代码有效，null、""、属性不存在时候都为false
					可选，0个或者多个
					]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType mixed="true">
			<xsd:choice>
				<xsd:element ref="isNotEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isNotEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
			</xsd:choice>
			<xsd:attribute name="property" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>
							<![CDATA[
							必填，判断的属性名称
							]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="isEmpty">
		<xsd:annotation>
			<xsd:documentation>
					<![CDATA[
					判断节点，property为空的时候该节点的代码有效，null、""、属性不存在时候都为true
					可选，0个或者多个
					]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType mixed="true">
			<xsd:choice>
				<xsd:element ref="isNotEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isNotEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
			</xsd:choice>
			<xsd:attribute name="property" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>
						<![CDATA[
						必填，判断的属性名称
						]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="isEqual">
		<xsd:annotation>
			<xsd:documentation>
				<![CDATA[
				判断节点，比较property值为比较值或者比较属性值的时候有效;
				可以是属性和指定值比较，也可以属性和属性比较
				可选，0个或多个
				]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType mixed="true">
			<xsd:choice>
				<xsd:element ref="isNotEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isNotEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
			</xsd:choice>
			<xsd:attribute name="property" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>
						<![CDATA[
						必填，用户比较的属性
						]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="compareValue" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>
						<![CDATA[
						和compareProperty进行二选一，比较的值为固定值
						]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="compareProperty" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>
						<![CDATA[
						和compareValue进行二选一，不为空时候为属性和属性进行比较
						]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="isNotEqual" >
		<xsd:annotation>
			<xsd:documentation>
				<![CDATA[
				判断节点，比较property值不为比较值或者比较属性值的时候有效;
				可以是属性和指定值比较，也可以属性和属性比较
				可选，0个或多个
				]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType mixed="true">
			<xsd:choice>
				<xsd:element ref="isNotEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isNotEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
			</xsd:choice>
			<xsd:attribute name="property" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>
						<![CDATA[
						必填，用户比较的属性
						]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="compareValue" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>
						<![CDATA[
						和compareProperty进行二选一，比较的值为固定值
						]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="compareProperty" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>
						<![CDATA[
						和compareValue进行二选一，不为空时候为属性和属性进行比较
						]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="mappers">
		<xsd:annotation>
			<xsd:documentation>
				<![CDATA[
				单个逻辑执行语句，和url表一一映射，其中id和sys_url_tab，url_id字段一致
				]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="mapper" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>
							<![CDATA[
							单个逻辑执行语句，和url表一一映射，其中id和sys_url_tab，url_id字段一致
							]]>
						</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="sql" minOccurs="1" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>
										<![CDATA[
										执行的单条逻辑语句
										至少有一个
										]]>
									</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType mixed="true">
									<xsd:choice minOccurs="0" maxOccurs="unbounded">
										<xsd:element ref="isNotEmpty"></xsd:element>
										<xsd:element ref="isEmpty"></xsd:element>
										<xsd:element ref="isNotEqual"></xsd:element>
										<xsd:element ref="isEqual"></xsd:element>
									</xsd:choice>
									<xsd:attribute name="key" type="xsd:string">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
												可选，sql在当前mapper中唯一
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="dynamic" default="false"
										type="xsd:boolean">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
												动态分页查询查询语句，queryService有效，默认为false，为true代表获取的数据分页量由用户自主控制
												否则系统会跟踪数据库类型进行分页语句的拼装
												可选
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="resultType" default="list">
										<xsd:annotation>
											<xsd:documentation>    
												<![CDATA[
												查询返回类型，ajaxService有效， list/map/string/page；四个操作,默认为list
												list 代表返回list
												map 代表返回map
												string 代表返回String
												page 返回分页对象 paginForm
												]]>
											</xsd:documentation>
										</xsd:annotation>
										<xsd:simpleType>
											<xsd:restriction base="xsd:NMTOKEN">
												<xsd:enumeration value="list" />
												<xsd:enumeration value="map" />
												<xsd:enumeration value="string" />
												<xsd:enumeration value="page" />
											</xsd:restriction>
										</xsd:simpleType>
									</xsd:attribute>
									<xsd:attribute name="operator" default="execute">
										<xsd:annotation>
											<xsd:documentation>    
												<![CDATA[
												sql操作类型，值为select/insert_file/del_file/execute/callback；五个操作,默认为execute
												execute 代表执行sql语句
												select 代表执行查询语句
												insert_file 代表插入文件
												del_file 代表删除文件
												callback 代表回调方法
												]]>
											</xsd:documentation>
										</xsd:annotation>
										<xsd:simpleType>
											<xsd:restriction base="xsd:NMTOKEN">
												<xsd:enumeration value="execute" />
												<xsd:enumeration value="select" />
												<xsd:enumeration value="insert_file" />
												<xsd:enumeration value="del_file" />
												<xsd:enumeration value="callback" />
											</xsd:restriction>
										</xsd:simpleType>
									</xsd:attribute>
									<xsd:attribute name="class" type="xsd:string">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
												可选，用于opertor为callbak回调适用的类
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="iterfields" default=""
										type="xsd:string">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
													可选，需要迭代执行的字段，用了这个属性，根据实际情况会产生多条执行语句；
													比如页面是主订单和字订单时，子订单有多条，实际情况是保存了主订单，还需要保存子订单（多条）
													可以用到该字段，比如子订单的字段分别有sub_order_id、sub_order_no、sub_order_name等
													这里的字段就填写成sub_order_id,sub_order_no,sub_order_name
													注：和iterfieldsplit有关系，当iterfieldsplit不为空试试，按照页面提交的值进行分割生成迭代语句
													当iterfieldsplit为空，则按照网页上提交的参数个数生成迭代语句
													operator=execute时候有效
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="iterfieldsplit" default=""
										type="xsd:string">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
													可选，和iterfields配合使用
													当这个字段不为空时，需要迭代属性值（迭代的属性参考字段iterfields）就按照这个字符串进行分割
													如iterfields=rights,name，iterFieldSplit=“---”
													页面提交的参数rights=101---102name=101name---102name，迭代的次数为2
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="filewname" default="_FILE_"
										type="xsd:string">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
													可选，有附件上传的时候使用，不存在该属性时，值为_FILE_；
													为网页上的附件控件（如  <input type="file" name="_FILE_">;）
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="fileindex" default=""
										type="xsd:string">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
												可选，配合filewname使用，默认为空，为多类附件上传的时候使用，如头像上传、身份证上传
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="id" type="xsd:string">
							<xsd:annotation>
								<xsd:documentation>
									<![CDATA[
									唯一值，和url表一一映射，其中id和sys_url_tab，url_id字段一致
									]]>
								</xsd:documentation>
							</xsd:annotation>
						</xsd:attribute>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== huangtingliu/lanting/WebRoot/WEB-INF/sysxml/execsql/yellowpage.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappers xmlns="http://www.weimingfj.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://itest.56913.com:20080/xsd/mappers.xsd">
<!-- 物流黄页 -->
	<mapper id="yellowpage">
	<sql key="yellowpage"  operator="select" resultType="paging"  >
		select 
		<isEmpty property="query_count">
			company_id,company_name,business_scope,business_lines,company_desc,addr,contacts,contact_tel,type
		</isEmpty>
		<isNotEmpty property="query_count"> count(1) </isNotEmpty>
		from (
		
		SELECT
			company_id,
			company_name,
			business_scope,
			business_lines,
			company_desc,
			addr,
			contacts,
			contact_tel,
		2 type,
		is_del,
		area_code
		FROM
			base_company_tab  
		union all 
		SELECT
			PARK_ID ,
			PARK_NAME ,
			 '',
			'',
			PARK_DESC ,
			PARK_ADDR,
			CON_MAN ,
			MOBILE ,1 type,
			is_del,
			area_code
		FROM
			base_park_tab 
		) a 
    where is_del='N' 
    and company_name is not null and company_name!='' 
   <!-- and business_scope is not null and business_scope!='' -->
  <!--   and business_lines is not null and business_lines!=''  -->
   <!-- and company_desc is not null and company_desc!='' -->
    and addr is not null and addr!='' 
    and contacts is not null and contacts!='' 
    and contact_tel is not null and contact_tel!=''
		<isNotEmpty property="areaCode">
			and a.area_code like '${areaCode}%' 
		</isNotEmpty>
		<isNotEmpty property="companyName">
			and a.company_name like '%${companyName}%' 
		</isNotEmpty>
		<isNotEmpty property="type">
			and a.type = '${type}' 
		</isNotEmpty>
		<isEmpty property="query_count">
		limit ${page_start},${rows}
		</isEmpty>
</sql>

	</mapper>
	<mapper id="yellowdetail">
		<sql key="yellowdetail" operator="select" resultType="map">
		select a.*,b.full_text area_name from base_company_tab a 
		left join base_area_tab b on a.area_code=b.code 
		where a.company_id=#{id}
	</sql>
	</mapper>
		<mapper id="yellowYqdetail">
		<sql key="yellowYqdetail" operator="select" resultType="map">
		select a.*,b.full_text area_name from base_park_tab a 
		left join base_area_tab b on a.area_code=b.code 
		where a.park_id=#{id}
	</sql>
	</mapper>
</mappers>

=== huangtingliu/lanting/WebRoot/WEB-INF/sysxml/execsql/truck.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappers xmlns="http://www.weimingfj.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://itest.56913.com:20080/xsd/mappers.xsd">

	<!-- 首页加载货源 -->
	<mapper id="loadTruckInfo">
		<sql key="loadTruckInfo" operator="select" resultType="paging">
			SELECT
			<isNotEmpty property="query_count"> count(1) </isNotEmpty>
			<isEmpty property="query_count"> * </isEmpty>
			FROM(
			select DATE_FORMAT(c.ADD_TIME,"%Y-%m-%d %T")
			pub_date1,c.*,c.user_name
			MEMBER_NAME,( select count(1) from collect
			where collect_type=2 and collect_id=c.yl_id and
			member_id='$_CRU_USER_ID_$' ) as TYPE,(select user_auth_status from
			sys_user_tab where user_id=c.user_id) ua,(select company_auth_status
			from sys_user_tab where user_id=c.user_id) ca,
			(select count(1) from yb_vip_user_today_his yvut where yvut.userid='$_CRU_USER_ID_$' and yvut.code='CYXX' and yvut.object_id=c.yl_id and source='WEB') isshow 
			from (
			SELECT y.*,DATE_FORMAT(y.END_DATE,"%Y-%m-%d") END_DATE1
			,DATE_FORMAT(st.LAST_LOC_TIME,"%Y-%m-%d %T")
			F_LAST_LOC_TIME,st.LAST_LOC_LNG,st.LAST_LOC_LAT,st.LAST_LOC_ADDR,st.LOC_WAY_FROM
			as FROM_TYPE,
			a.FULL_TEXT YL_SOURCE_TEXT,
			(SELECT group_concat(bb.FULL_TEXT) text FROM v_area_tab bb WHERE FIND_IN_SET(bb.`CODE`, y.destination)) yl_dest_text 
			from yl_tab y
			left join v_area_tab a on a.`CODE`=y.YL_SOURCE
			LEFT JOIN sys_truck_tab st on
			y.TRUCK_PLATE=st.TRUCK_PLATE and
			st.TRUCK_PLATE_COLOR=y.TRUCK_PLATE_COLOR
			where y.is_delete='N' and
			y.valid=1 
			<isNotEmpty property="vip">
				and y.VIP=#{vip} 
			</isNotEmpty>
			
			and y.end_date >=
			now()
			<isNotEmpty property="is_online">
				AND st.LAST_LOC_LNG IS NOT NULL AND
				st.LAST_LOC_LAT IS NOT NULL and
				st.LAST_LOC_TIME >
				date_sub(curdate(), interval '1' day)
			</isNotEmpty>
			<isNotEmpty property="topTime">
				and y.add_time > #{topTime}
			</isNotEmpty>
			<isNotEmpty property="bottomTime">
				and y.add_time &lt;= #{bottomTime}
			</isNotEmpty>

			<isNotEmpty property="QUERY_SOURCE">
				and y.yl_source like
				'${QUERY_SOURCE}%'
			</isNotEmpty>
			<isNotEmpty property="QUERY_DESTINATION">
				and y.destination REGEXP
				'(^(${QUERY_DESTINATION})\d*,?)|(,(${QUERY_DESTINATION})\d*,?)'
			</isNotEmpty>
			<isNotEmpty property="TRUCK_TYPE">
				and y.TRUCK_TYPE =#{TRUCK_TYPE}
			</isNotEmpty>
			<isNotEmpty property="TRUCK_LENGTH">
				and y.TRUCK_LENGTH  = '${TRUCK_LENGTH}' 
			</isNotEmpty>
			<isNotEmpty property="TRUCK_LOAD">
				and y.TRUCK_LOAD  = '${TRUCK_LOAD}'  
			</isNotEmpty>
			<isNotEmpty property="TRUCK_PLATE">
				and y.TRUCK_PLATE  LIKE '%${TRUCK_PLATE}%'  
			</isNotEmpty>
			<isNotEmpty property="vip">
				and y.vip = ${vip}
			</isNotEmpty>
			ORDER BY y.ADD_TIME desc
			) c
			) aa
			<isEmpty property="query_count">
 				<isNotEmpty property="pager">
 					LIMIT ${PAGESTART}, ${PAGENUM}
 				</isNotEmpty>	
			</isEmpty>
		</sql>
	</mapper>
	<!-- 获取单个车源信息 -->
	<mapper id="getTruckInfoById">
		<sql key="getTruckInfoById" resultType="map" operator="select">
			select DATE_FORMAT(c.ADD_TIME,"%Y-%m-%d %T") f_pub_time, st.LAST_LOC_ADDR,c.*,a.FULL_TEXT
			YL_SOURCE_TEXT,(SELECT group_concat(aa.FULL_TEXT) text FROM
			v_area_tab aa WHERE FIND_IN_SET(aa.`CODE`, c.destination))
			yl_dest_text from yl_tab c
			left join v_area_tab a on a.`CODE`=c.YL_SOURCE 
			LEFT JOIN sys_truck_tab st on st.TRUCK_PLATE=c.TRUCK_PLATE 
			where 1=1 AND c.yl_id =#{TRUCK_ID}
		</sql>
	</mapper>

	<!-- 添加单个车源信息 -->
	<mapper id="addTruckInfo">
		<sql key="note_save" operator="execute">
			INSERT INTO yl_tab(yl_id,yl_source, destination, <!-- truck_plate, --> truck_type,
			truck_length,  truck_load, driver_name,
			driver_mobile, contact_name, contact_mobile, is_delete, tenant_id,
			user_name, user_id, really_name, valid, add_time, way_from, yl_no,
			DRIVER_IDCARD, YL_TYPE, PAY_METHOD, IS_GROUP, START_DATE, END_DATE,
			ROAD, remark,CONTACT_COMPANY,PRICE,UNIT,	VIP)
			 select UUID(),#{SOURCE}, #{DESTINATION}, <!-- #{TRUCK_PLATE}, -->
			#{TRUCK_TYPE}, #{TRUCK_LENGTH},  #{TRUCK_LOAD},
			#{CONTACT_NAME}, #{CONTACT_MOBILE}, #{CONTACT_NAME},
			#{CONTACT_MOBILE}, 'N', '-1', '$_CRU_USER_NAME_$', '$_CRU_USER_ID_$',
			'$_CRU_REAL_NAME_$', 1, NOW(), '2', '', '', 1, 2, 2,
			#{START_DATE}, #{END_DATE}, #{TRUCK_LOAD}, '${REMARK2}',#{CONTACT_COMPANY}, #{yf},#{truck_yf_unit},${is_truck_vip} from sys_user_tab  where user_id ='$_CRU_USER_ID_$'


		</sql>
		<sql operator="callback" class="pointsCallBack" />

	</mapper>
	
	<!-- 添加收藏 -->
	<mapper id="addTruckCollect">
		<sql key="addTruckCollect" operator="execute">
			INSERT into collect(MEMBER_ID,COLLECT_ID,COLLECT_TYPE)VALUES(#{MEMBER_ID},#{COLLECT_ID},#{COLLECT_TYPE})	
		</sql>
	</mapper>
	
		<!-- 取消收藏 -->
	<mapper id="deleteTruckCollect">
		<sql key="deleteTruckCollect" operator="execute">
			DELETE FROM collect WHERE COLLECT_ID=#{COLLECT_ID} and MEMBER_ID=#{MEMBER_ID}	
		</sql>
	</mapper>
	<!-- 我的车队列表 -->
	<mapper id="myTruckList">
			<sql key="myTruckList" operator="select" resultType="paging">
				<isEmpty property="query_count">
				    select a.*,b.orderCount,c.STATUSOCOUNT from(
				</isEmpty>
				SELECT
				<isNotEmpty property="query_count"> count(1) </isNotEmpty>
				<isEmpty property="query_count">
					t.id,
					t.team_name,
					t.INVITE_TO_TEL,
					t.STATUS,
					t.reason,
					su.TEL,
					su.USER_ID,
					su.USER_CODE,
					su.USER_NAME,
					st.TRUCK_PLATE,
					st.TRUCK_ID,
					st.TRUCK_TYPE,
					st.TRUCK_LENGTH,
					st.TRUCK_TON,
					st.DRIVER_NAME,
					st.DRIVER_TEL,
					st.LAST_LOC_ADDR,
					DATE_FORMAT(st.LAST_LOC_TIME,'%m-%d %H:%i') LAST_LOC_TIME,
					st.LOC_WAY_FROM,
					st.LAST_LOC_LAT,
					st.LAST_LOC_LNG,
					su.LOC_STATUS
				</isEmpty>
				FROM
				truck_team_tab t
				LEFT JOIN sys_user_tab su ON t.invite_to_user = su.user_id
				LEFT JOIN sys_truck_tab st ON su.truck_id = st.TRUCK_ID
				WHERE
				t.user_id = '$_CRU_USER_ID_$'
				AND t.is_del = 'N'
				<isNotEmpty property="DRIVER_NAME">
					and su.USER_NAME like "%${DRIVER_NAME}%"
				</isNotEmpty>
				<isNotEmpty property="STATUS">
					and t.STATUS =#{STATUS}
				</isNotEmpty>
				<isNotEmpty property="DRIVER_TEL">
					and su.TEL like "%${DRIVER_TEL}%"
				</isNotEmpty>
				<isNotEmpty property="TRUCK_TON">
					and st.TRUCK_TON =#{TRUCK_TON}
				</isNotEmpty>
				<isNotEmpty property="TRUCK_LENGTH">
					and st.TRUCK_LENGTH =#{TRUCK_LENGTH}
				</isNotEmpty>
				<isNotEmpty property="TRUCK_TYPE">
					and st.TRUCK_TYPE =#{TRUCK_TYPE}
				</isNotEmpty>
				<isNotEmpty property="TRUCK_PLATE">
					and st.TRUCK_PLATE like "%${TRUCK_PLATE}%" and t.STATUS='2'
				</isNotEmpty>
				<isEmpty property="query_count">
					order by t.team_name ,t.reply_date desc
					<isNotEmpty property="pager">
						LIMIT ${PAGESTART}, ${PAGENUM}
					</isNotEmpty>
					)a LEFT JOIN (
					SELECT
					count(*) orderCount,
					ot.driver_id
					FROM
					transport_order_tab ot
					WHERE
					ot.is_del = 'N'
					AND ot.create_user_id = '$_CRU_USER_ID_$'
					GROUP BY
					driver_id
					) b ON a.USER_ID = b.driver_id
					LEFT JOIN( SELECT
					count(1) STATUSOCOUNT ,
					ott.driver_id
					FROM
					transport_order_tab ott
					WHERE
					ott.is_del = 'N' and (ott.order_status ='1' or ott.order_status='3' or
					ott.order_status='4' or ott.order_status='5' or
					ott.order_status='0' )
					AND ott.create_user_id = '$_CRU_USER_ID_$'
					GROUP BY
					driver_id
					) c ON a.USER_ID = c.driver_id
				</isEmpty>
			</sql>
		</mapper>
<!-- 验证是否向用户发出了车队邀请 -->
<mapper  id="validateUser">
	<sql key="validateUser" operator="select" resultType="map" >
		select count(1) userCount,status from truck_team_tab where user_id='$_CRU_USER_ID_$' and is_del='N' and status!='3' and  
		invite_to_user in(select user_id from sys_user_tab where tel=#{tel})
</sql>
</mapper>
<!-- 保存车辆车队所属 -->
<mapper id="saveTruck">
	<sql key="saveTruck"  operator="execute">
		update truck_team_tab set team_name=#{team_name} where id=#{TRUCK_ID}
   </sql>
</mapper>
<!-- 车辆的详情 -->
<mapper id="vipTruckDetail">
	<sql key="vipTruckDetail" operator="select" resultType="paging">
<isEmpty property="query_count">select a.*,b.photoCount,ba.full_text loading_addr_text,bt.full_text receive_addr_text from(</isEmpty>	SELECT <isNotEmpty property="query_count"> count(1) </isNotEmpty>
<isEmpty property="query_count">
				ot.ORDER_ID,ot.ORDER_NO,ot.ORDER_STATUS,DATE_FORMAT(ot.arrive_date,"%Y-%m-%d") arrive_date, DATE_FORMAT(ot.CREATE_DATE,"%Y-%m-%d %T") CREATE_DATE,
				ot.FEE,ot.CONSIGNOR,ot.CONSIGNOR_TEL,ot.LOADING_ADDR,ot.CONSIGNEE,ot.RECEIVE_ADDR,ot.consignee_tel,ot.loading_code,ot.receive_code 
</isEmpty>
				 from transport_order_tab ot  where  ot.driver_id=#{userId} and ot.is_del='N' and ot.create_user_id='$_CRU_USER_ID_$' 
<isEmpty property="query_count">
        order by CREATE_DATE desc 
				<isNotEmpty property="pager">  
						LIMIT ${PAGESTART}, ${PAGENUM} 
				</isNotEmpty> 
			) a  left join base_area_tab ba on a.loading_code=ba.code 
				 left join base_area_tab bt on a.receive_code=bt.code 
				 left join (select sum(if(pic1 is null or pic1='',0,1)+IF(pic2 is null or pic2='',0,1)+if(pic3 is null or pic3='',0,1)) photoCount,order_id from transport_order_proc_tab t GROUP BY order_id) b on a.order_id=b.order_id
</isEmpty>
</sql>
</mapper>
<!-- 获取车辆的GPS -->
<mapper id="getGPS">
  <sql key="getGPS" operator="select" resultType="map">
	select LAST_LOC_LAT,LAST_LOC_LNG,b.TRUCK_ID,DRIVER_TEL,a.LOC_STATUS from sys_truck_tab b left join sys_user_tab a on a.tel=#{tel} where b.truck_id=#{truckId}
	</sql>
</mapper>
</mappers>

=== huangtingliu/lanting/WebRoot/WEB-INF/sysxml/execsql/transport.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappers xmlns="http://www.weimingfj.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://itest.56913.com:20080/xsd/mappers.xsd">

	<mapper id="loadTransport">
		<sql key="msginstall_tab" sqlType="query" resultType="paging"
			operator="select" dynamic="true">
			<isEmpty property="query_count">select * from(</isEmpty>
			SELECT
			<isNotEmpty property="query_count"> count(1) </isNotEmpty>
			<isEmpty property="query_count">
				ot.order_id,
				ot.driver_id,
				ot.order_no,
				ot.reason,
				ot.is_sign,
				ot.cargo_name,
				ot.cargo_size,
				ot.cargo_size_type,
				ot.receive_code,
				DATE_FORMAT(ot.arrive_date,'%m-%d') arrive_date,
				ot.fee,
				ot.loading_code,
				ot.order_status,
				su.user_name,
				su.tel,
				st.TRUCK_PLATE
			</isEmpty>
			FROM
			`transport_order_tab` ot
			LEFT JOIN sys_user_tab su ON ot.driver_id
			= su.user_id
			LEFT JOIN sys_truck_tab st on su.truck_id=st.TRUCK_ID
			where 1=1 and ot.create_user_id='$_CRU_USER_ID_$'and ot.is_del='N'
			<isNotEmpty property="ORDER_STATUS">
				and ot.order_status=#{ORDER_STATUS}
			</isNotEmpty>
			<isNotEmpty property="TRUCK_PLATE">
				and st.TRUCK_PLATE
				like'%${TRUCK_PLATE}%'
			</isNotEmpty>
			<isNotEmpty property="ORDER_NO">
				and ot.ORDER_NO like'%${ORDER_NO}%'
			</isNotEmpty>
			<isNotEmpty property="USER_NAME">
				and su.user_name like'%${USER_NAME}%'
			</isNotEmpty>
			<isNotEmpty property="TEL">
				and su.tel like'%${TEL}%'
			</isNotEmpty>
			<isEmpty property="query_count">
				order by ot.create_date desc
				<isNotEmpty property="pager">
					LIMIT ${PAGESTART}, ${PAGENUM}
				</isNotEmpty>
				)a
			</isEmpty>
		</sql>
	</mapper>

	<mapper id="valideOrderNO">
		<sql key="select_GPS" sqlType="query" resultType="map" dynamic="false"
			operator="select">
			select count(1) orderCount from transport_order_tab where
			ORDER_NO=#{ORDER_NO} and is_del='N' and create_user_id
			='$_CRU_USER_ID_$'
			<isNotEmpty property="ID">
				and order_id!=#{ID}
			</isNotEmpty>
		</sql>
	</mapper>

	<mapper id="addTransportServic">
		<sql key="msginstall_tab" operator="execute">
			INSERT INTO
			`transport_order_tab`
			(ORDER_ID,DRIVER_ID,REMARK,FEE,ARRIVE_DATE,RECEIVE_ADDR,RECEIVE_CODE,CONSIGNEE_TEL,CONSIGNEE,LOADING_ADDR,LOADING_CODE,CONSIGNOR_TEL,CONSIGNOR,CARGO_SIZE_TYPE,CARGO_SIZE,CARGO_NAME,ORDER_NO,create_user_id,create_date,order_status)
			VALUES
			(#{ORDER_ID},#{userId},#{REMARK},#{FEE},#{ARRIVE_DATE},#{RECEIVE_ADDR},#{RECEIVE_CODE},#{CONSIGNEE_TEL},#{CONSIGNEE},#{LOADING_ADDR},#{LOADING_CODE},#{CONSIGNOR_TEL},#{CONSIGNOR},#{CARGO_SIZE_TYPE},#{CARGO_SIZE},#{CARGO_NAME},#{ORDER_NO},'$_CRU_USER_ID_$',now(),'0')
		</sql>
		<sql operator="callback" class="pointsCallBack" />
	</mapper>

	<mapper id="updateTransportServic">
		<sql key="msginstall_tab" operator="execute">
			update transport_order_tab set
			DRIVER_ID=#{userId},REMARK=#{REMARK},FEE=#{FEE},ARRIVE_DATE=#{ARRIVE_DATE},
			RECEIVE_ADDR=#{RECEIVE_ADDR},RECEIVE_CODE=#{RECEIVE_CODE},CONSIGNEE_TEL=#{CONSIGNEE_TEL},CONSIGNEE=#{CONSIGNEE},LOADING_ADDR=#{LOADING_ADDR}
			,LOADING_CODE=#{LOADING_CODE},CONSIGNOR_TEL=#{CONSIGNOR_TEL},CONSIGNOR=#{CONSIGNOR},CARGO_SIZE_TYPE=#{CARGO_SIZE_TYPE},CARGO_NAME=#{CARGO_NAME},ORDER_NO=#{ORDER_NO}
			<isNotEmpty property="status">
				<isEqual property="status" compareValue="2">
					,order_status='0'
				</isEqual>
			</isNotEmpty>
			where order_id=#{id}
		</sql>
	</mapper>

	<mapper id="removeTransport">
		<sql key="msginstall_tab" operator="execute">
			update transport_order_tab set is_del='Y',del_date=now() where
			order_id=#{id}
		</sql>
	</mapper>

	<mapper id="endTransport">
		<sql key="msginstall_tab"  operator="execute">
			update transport_order_tab set order_status='6' where order_id=#{id}
	   </sql>
	</mapper>
	
	<mapper id="getImgPath">
		<sql key="msginstall_tab" sqlType="query" resultType="list" operator="select" dysql="true">
			select pic1,pic2,pic3,title from transport_order_proc_tab where 1=1  
		   		and order_id=#{id} order by report_date desc
		</sql>
	</mapper>
	<mapper id = "msginstall_tab">
		<sql key="msginstall_tab" sqlType="query" resultType="map" operator="select" >
			select a.user_name,a.tel,b.TRUCK_PLATE,b.TRUCK_LENGTH,b.TRUCK_TON,TRUCK_TYPE from sys_user_tab a LEFT JOIN sys_truck_tab b on a.truck_id=b.TRUCK_ID where a.user_id=#{id}
		</sql>
	</mapper>
	
	<mapper id="orderIsExist">
		<sql operator="select" resultType="string">
			select count(1) from transport_order_cargouser_tab where order_no =#{orderNo} and is_del='N'
		</sql>
	</mapper>
</mappers>
