=== huangtingliu/lanting/WebRoot/WEB-INF/sysxml/mappers.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.weimingfj.com/xsd/mappers" xmlns="http://www.weimingfj.com/xsd/mappers"
	elementFormDefault="qualified">
	<xsd:element name="isNotEmpty">
		<xsd:annotation>
			<xsd:documentation>
					<![CDATA[
					判断节点，property不为空的时候该节点的代码有效，null、""、属性不存在时候都为false
					可选，0个或者多个
					]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType mixed="true">
			<xsd:choice>
				<xsd:element ref="isNotEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isNotEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
			</xsd:choice>
			<xsd:attribute name="property" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>
							<![CDATA[
							必填，判断的属性名称
							]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="isEmpty">
		<xsd:annotation>
			<xsd:documentation>
					<![CDATA[
					判断节点，property为空的时候该节点的代码有效，null、""、属性不存在时候都为true
					可选，0个或者多个
					]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType mixed="true">
			<xsd:choice>
				<xsd:element ref="isNotEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isNotEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
			</xsd:choice>
			<xsd:attribute name="property" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>
						<![CDATA[
						必填，判断的属性名称
						]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="isEqual">
		<xsd:annotation>
			<xsd:documentation>
				<![CDATA[
				判断节点，比较property值为比较值或者比较属性值的时候有效;
				可以是属性和指定值比较，也可以属性和属性比较
				可选，0个或多个
				]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType mixed="true">
			<xsd:choice>
				<xsd:element ref="isNotEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isNotEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
			</xsd:choice>
			<xsd:attribute name="property" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>
						<![CDATA[
						必填，用户比较的属性
						]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="compareValue" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>
						<![CDATA[
						和compareProperty进行二选一，比较的值为固定值
						]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="compareProperty" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>
						<![CDATA[
						和compareValue进行二选一，不为空时候为属性和属性进行比较
						]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="isNotEqual" >
		<xsd:annotation>
			<xsd:documentation>
				<![CDATA[
				判断节点，比较property值不为比较值或者比较属性值的时候有效;
				可以是属性和指定值比较，也可以属性和属性比较
				可选，0个或多个
				]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType mixed="true">
			<xsd:choice>
				<xsd:element ref="isNotEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isNotEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
			</xsd:choice>
			<xsd:attribute name="property" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>
						<![CDATA[
						必填，用户比较的属性
						]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="compareValue" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>
						<![CDATA[
						和compareProperty进行二选一，比较的值为固定值
						]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="compareProperty" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>
						<![CDATA[
						和compareValue进行二选一，不为空时候为属性和属性进行比较
						]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="mappers">
		<xsd:annotation>
			<xsd:documentation>
				<![CDATA[
				单个逻辑执行语句，和url表一一映射，其中id和sys_url_tab，url_id字段一致
				]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="mapper" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>
							<![CDATA[
							单个逻辑执行语句，和url表一一映射，其中id和sys_url_tab，url_id字段一致
							]]>
						</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="sql" minOccurs="1" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>
										<![CDATA[
										执行的单条逻辑语句
										至少有一个
										]]>
									</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType mixed="true">
									<xsd:choice minOccurs="0" maxOccurs="unbounded">
										<xsd:element ref="isNotEmpty"></xsd:element>
										<xsd:element ref="isEmpty"></xsd:element>
										<xsd:element ref="isNotEqual"></xsd:element>
										<xsd:element ref="isEqual"></xsd:element>
									</xsd:choice>
									<xsd:attribute name="key" type="xsd:string">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
												可选，sql在当前mapper中唯一
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="dynamic" default="false"
										type="xsd:boolean">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
												动态分页查询查询语句，queryService有效，默认为false，为true代表获取的数据分页量由用户自主控制
												否则系统会跟踪数据库类型进行分页语句的拼装
												可选
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="resultType" default="list">
										<xsd:annotation>
											<xsd:documentation>    
												<![CDATA[
												查询返回类型，ajaxService有效， list/map/string/page；四个操作,默认为list
												list 代表返回list
												map 代表返回map
												string 代表返回String
												page 返回分页对象 paginForm
												]]>
											</xsd:documentation>
										</xsd:annotation>
										<xsd:simpleType>
											<xsd:restriction base="xsd:NMTOKEN">
												<xsd:enumeration value="list" />
												<xsd:enumeration value="map" />
												<xsd:enumeration value="string" />
												<xsd:enumeration value="page" />
											</xsd:restriction>
										</xsd:simpleType>
									</xsd:attribute>
									<xsd:attribute name="operator" default="execute">
										<xsd:annotation>
											<xsd:documentation>    
												<![CDATA[
												sql操作类型，值为select/insert_file/del_file/execute/callback；五个操作,默认为execute
												execute 代表执行sql语句
												select 代表执行查询语句
												insert_file 代表插入文件
												del_file 代表删除文件
												callback 代表回调方法
												]]>
											</xsd:documentation>
										</xsd:annotation>
										<xsd:simpleType>
											<xsd:restriction base="xsd:NMTOKEN">
												<xsd:enumeration value="execute" />
												<xsd:enumeration value="select" />
												<xsd:enumeration value="insert_file" />
												<xsd:enumeration value="del_file" />
												<xsd:enumeration value="callback" />
											</xsd:restriction>
										</xsd:simpleType>
									</xsd:attribute>
									<xsd:attribute name="class" type="xsd:string">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
												可选，用于opertor为callbak回调适用的类
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="iterfields" default=""
										type="xsd:string">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
													可选，需要迭代执行的字段，用了这个属性，根据实际情况会产生多条执行语句；
													比如页面是主订单和字订单时，子订单有多条，实际情况是保存了主订单，还需要保存子订单（多条）
													可以用到该字段，比如子订单的字段分别有sub_order_id、sub_order_no、sub_order_name等
													这里的字段就填写成sub_order_id,sub_order_no,sub_order_name
													注：和iterfieldsplit有关系，当iterfieldsplit不为空试试，按照页面提交的值进行分割生成迭代语句
													当iterfieldsplit为空，则按照网页上提交的参数个数生成迭代语句
													operator=execute时候有效
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="iterfieldsplit" default=""
										type="xsd:string">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
													可选，和iterfields配合使用
													当这个字段不为空时，需要迭代属性值（迭代的属性参考字段iterfields）就按照这个字符串进行分割
													如iterfields=rights,name，iterFieldSplit=“---”
													页面提交的参数rights=101---102name=101name---102name，迭代的次数为2
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="filewname" default="_FILE_"
										type="xsd:string">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
													可选，有附件上传的时候使用，不存在该属性时，值为_FILE_；
													为网页上的附件控件（如  <input type="file" name="_FILE_">;）
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="fileindex" default=""
										type="xsd:string">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
												可选，配合filewname使用，默认为空，为多类附件上传的时候使用，如头像上传、身份证上传
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="id" type="xsd:string">
							<xsd:annotation>
								<xsd:documentation>
									<![CDATA[
									唯一值，和url表一一映射，其中id和sys_url_tab，url_id字段一致
									]]>
								</xsd:documentation>
							</xsd:annotation>
						</xsd:attribute>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== huangtingliu/lanting/WebRoot/WEB-INF/sysxml/execsql/cargo.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappers xmlns="http://www.weimingfj.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://itest.56913.com:20080/xsd/mappers.xsd">
	<!-- 首页加载货源 -->
	<mapper id="loadCargoInfo">
		<sql key="loadCargoInfo" operator="select" resultType="paging">
			select
			<isNotEmpty property="query_count"> count(1) </isNotEmpty>
			<isEmpty property="query_count">
				DATE_FORMAT(c.create_time,"%Y-%m-%d %T") create_time1,c.*,c.pub_name MEMBER_NAME,( select count(1) from
				collect where 1=1 and member_id='$_CRU_USER_ID_$'
				and collect_type=1 and collect_id=c.SEQ ) as TYPE,(select
				user_auth_status from sys_user_tab where user_id=c.user_id)
				ua,(select company_auth_status from sys_user_tab where
				user_id=c.user_id) ca,
				(select count(1) from yb_vip_user_today_his yvut where yvut.userid='$_CRU_USER_ID_$' and yvut.code='HYXX' and yvut.object_id=c.SEQ and source='WEB') isshow 
			</isEmpty>
			from sys_cargo_tab c where 1=1 and c.is_delete='N'  
			<isNotEmpty property="IS_VIP">
				and c.VIP = #{IS_VIP}
			</isNotEmpty>
			<isNotEmpty property="QUERY_SOURCE">
				and c.S_CODE_VAL like '${QUERY_SOURCE}%'
			</isNotEmpty>
			<isNotEmpty property="QUERY_DESTINATION">
				and c.T_CODE_VAL like '${QUERY_DESTINATION}%'
			</isNotEmpty>
			<isNotEmpty property="QUERY_TRUCK_TYPE">
				and c.C_TYPE = '${QUERY_TRUCK_TYPE}'
			</isNotEmpty>
			<isNotEmpty property="QUERY_TRUCK_LENGHT">
				and c.C_LENGTH = ${QUERY_TRUCK_LENGHT}
			</isNotEmpty>
			<isNotEmpty property="QUERY_TRUCK_LOAD">
				and c.G_SIZE = ${QUERY_TRUCK_LOAD}
			</isNotEmpty>
      <isNotEmpty property="QUERY_TRUCK_LOAD_TYPE">
        and c.G_TYPE = '${QUERY_TRUCK_LOAD_TYPE}'
      </isNotEmpty>

			<isNotEmpty property="topTime">
				and c.CREATE_TIME >DATE_FORMAT(#{topTime},"%Y-%m-%d %T")
			</isNotEmpty>
			<isNotEmpty property="bottomTime">
				and c.CREATE_TIME &lt; DATE_FORMAT(#{bottomTime},"%Y-%m-%d %T")
			</isNotEmpty>
			<isNotEmpty property="vip">
				and c.vip = ${vip}
			</isNotEmpty>
			<isEmpty property="query_count">
				ORDER BY c.CREATE_TIME desc
				<isNotEmpty property="pager">
					LIMIT ${PAGESTART}, ${PAGENUM}
				</isNotEmpty>
			</isEmpty>
		</sql>
	</mapper>
	<!-- 获取单个货源信息 -->
	<mapper id="getCargoInfoById">
		<sql key="getCargoInfoById" resultType="map" operator="select">
			select DATE_FORMAT(c.CREATE_TIME,"%Y-%m-%d %T") f_pub_time, c.*
			from sys_cargo_tab c where 1=1 and c.seq=#{CARGO_ID}
		</sql>
	</mapper>

	<!-- 添加单个货源信息 -->
	<mapper id="addCargoInfo">

<!--  		<sql key="S_AREA" operator="select"> -->
<!--  			select full_text S_AREA1 from base_area_tab t where t.code= #{S_CODE_VAL} -->
<!--  		</sql> -->
<!--  		<sql key="T_AREA" operator="select"> -->
<!--  			select full_text T_AREA1 from base_area_tab t where t.code= #{T_CODE_VAL} -->
<!--  		</sql> -->
		<sql operator="callback" class="syncCargoCallBack" /><!-- 货源的uuid在这里生成,同步货源到嘉兴交易大厅 -->
		<sql key="addCargoInfo" operator="execute">
			INSERT INTO sys_cargo_tab
			(SEQ,CARGO_TIME_END,PRICE,UNIT,S_CODE_VAL,T_CODE_VAL,G_TYPE,G_SIZE,G_SIZE_TYPE,C_LENGTH,C_TYPE,CON_PHONE,CON_MAN,STATE,CREATE_TIME,PUB_NAME,PUB_MOBILE,remark,
			PUB_COMPANY,SEARCH_KEY,S_AREA,T_AREA,SOURCE_WAY,USER_ID, IS_DELETE,VIP)
			VALUES(#{cargoId},#{CARGO_TIME_END},#{yf},#{cargo_yf_unit},#{S_CODE_VAL},#{T_CODE_VAL},#{G_TYPE},#{G_SIZE},#{G_SIZE_TYPE},#{C_LENGTH},#{C_TYPE},#{CON_PHONE},#{CON_MAN},0,now(),
			(select user_name from sys_user_tab where user_id='$_CRU_USER_ID_$'),
			(select tel from sys_user_tab where user_id='$_CRU_USER_ID_$'),
			'${remark1}${REMARK2}',#{PUB_COMPANY},
			CONCAT((select city_text from base_area_tab t where t.code= #{S_CODE_VAL}),
			(select city_text from base_area_tab t where t.code= #{T_CODE_VAL}),#{G_SIZE},#{G_SIZE_TYPE},#{G_TYPE},#{C_LENGTH},'米',#{C_TYPE},DATE_FORMAT(now(),'%Y-%m-%d')),
			(select full_text S_AREA from base_area_tab t where t.code= #{S_CODE_VAL}),(select full_text T_AREA1 from base_area_tab t where t.code= #{T_CODE_VAL}),#{SOURCE_WAY},'$_CRU_USER_ID_$','N',${is_cargo_vip})
		</sql>
		<sql operator="callback" class="pointsCallBack" />
		<sql operator="callback" class="sendMsg" />

	</mapper>

	<!-- 获取动态信息货源 -->
	<mapper id="getSyncCargo">
		<sql key="getSyncCargo" resultType="list" operator="select">
			select u.user_name,c.S_AREA,c.T_AREA,c.CREATE_TIME 
			from sys_cargo_tab c
			LEFT JOIN sys_user_tab u on c.USER_ID = u.user_id
			where 
				c.is_delete = 'N'  and u.user_name !='' and u.is_del = 'N'
			ORDER BY c.CREATE_TIME desc
			LIMIT 100
		</sql>
	</mapper>
	<!-- 获取热门合作企业 -->
	<mapper id="getHotPartner">
		<sql key="getHotPartner" resultType="list" operator="select">
			SELECT
				con.content_id,
				jce.title
			FROM
				qhcms.jc_content con
			left join qhcms.jc_content_ext jce on jce.content_id = con.content_id
			WHERE
				channel_id = (select text from sys_dict_tab where type='QHCMS_CHANNEL_ID' and is_del='N')
			limit 10
		</sql>
	</mapper>

</mappers>

=== huangtingliu/lanting/WebRoot/WEB-INF/sysxml/execsql/user.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappers xmlns="http://www.weimingfj.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://itest.56913.com:20080/xsd/mappers.xsd">
<!-- 用户信息 -->
<!-- 获取认证信息 -->
	<mapper id="selectAllProv">
	  <sql key="selectAllProv" operator="select" resultType="map" >
	
		select user_auth_status,company_auth_status,company_id from sys_user_tab where user_id=#{user_id} 	

	</sql>
	</mapper>

<!-- 获取用户审核信息 -->
<mapper id="msginstallTab">
	<sql key="msginstallTab" operator="select" resultType="map" >  
    select * from (select user_auth_status,company_auth_status,user_id,user_name real_name_ur,id_no  id_no_ur,addr id_card_addr_ur,company company_name_cr,con_addr company_addr_cr  from sys_user_tab  where user_id='$_CRU_USER_ID_$') u LEFT JOIN    
(select  real_name,id_card_addr,id_no,id_card_back,id_card_front,user_id from user_auth_record_tab where type=1 and user_id='$_CRU_USER_ID_$'  order by  apply_date desc limit 0,1 ) p on u.user_id=p.user_id left join  
( select  company_name,registration_number,legal_person,trading_photo_path,business_license_number,business_license_number_path,store_photo_path,user_id from user_auth_record_tab where type=2 and user_id='$_CRU_USER_ID_$'  order by  apply_date desc limit 0,1   ) c on c.user_id=u.user_id 
  </sql>
</mapper>

<!-- 获取用户个人认证信息 -->
<mapper id="getUserAuditMsg">
	<sql key="getUserAuditMsg" operator="select" resultType="map" >
			select a.*,sut.user_auth_status,sut.user_name,sut.tel,sut.id_no id_no_text from  sys_user_tab sut LEFT JOIN  auth_personal_tab a on a.user_id=sut.user_id   WHERE sut.user_id='$_CRU_USER_ID_$' order by a.apply_date  desc 
   </sql>
</mapper>

<!-- 获取用户企业认证信息  -->
<mapper id="getCompanyAuditMsg">
	<sql key="getCompanyAuditMsg" operator="select" resultType="map" >
				select sut.company,sut.company_id,sut.company_auth_status,act.*,bat.full_text 
FROM  
	sys_user_tab sut 
LEFT JOIN auth_company_tab act ON act.user_id = sut.user_id 
left join base_area_tab bat on act.area_code=bat.code where sut.user_id='$_CRU_USER_ID_$'
order by act.apply_date  desc  
   </sql>
</mapper>

<!-- 车源 ：上架下架 -->
<mapper id="setTruckIsValid">
	<sql key="setTruckIsValid"  operator="execute">
		update yl_tab set valid=#{VALID} 
			<isEqual property="VALID" compareValue="1">  
									,START_DATE=now()
									,END_DATE=DATE_ADD(now(),INTERVAL 3 DAY),
										ADD_TIME=NOW()
							</isEqual>
where user_id=#{USER_ID} and yl_id=#{TRUCK_ID} 
   </sql>
</mapper>

<!-- 删除车源 -->
<mapper id="delYLorCargo">
	<sql key="delYLorCargo"  operator="execute">
					update 
<isNotEmpty property="type">  
	<isEqual property="type" compareValue="0">  
									yl_tab set IS_DELETE='Y' where yl_id=#{id}
							</isEqual>
			<isEqual property="type" compareValue="1">  
								 sys_cargo_tab set IS_DELETE='Y' where SEQ=#{id} 
							</isEqual>
        </isNotEmpty>
   </sql>
</mapper> 


<!-- 我的货源 -->
<mapper id="loadMyCargoInfo">
	<sql key="loadMyCargoInfo" operator="select" resultType="autoPaging" >
        select DATE_FORMAT(c.create_time,"%Y-%m-%d %T") create_time1, c.*,c.pub_name MEMBER_NAME,( select  count(1) from collect where member_id='$_CRU_USER_ID_$' and collect_type=1 and collect_id=c.SEQ ) as TYPE  from (
SELECT * from sys_cargo_tab c where 1=1 and is_delete='N' and c.USER_ID= '$_CRU_USER_ID_$' and is_show=#{is_show}  
<isNotEmpty property="CARGO_SOURCE">  
  	and c.S_AREA=#{CARGO_SOURCE}
	</isNotEmpty>
	<isNotEmpty property="CARGO_DEST">  
  	and c.T_AREA=#{CARGO_DEST} 
	</isNotEmpty>
 ORDER BY c.CREATE_TIME desc 
) c 
    </sql>
</mapper>

<!-- 我的车源 -->
<mapper id="loadMyTruckInfo">
	<sql key="loadMyTruckInfo" operator="select" resultType="autoPaging" >
       select DATE_FORMAT(c.ADD_TIME,"%Y-%m-%d %T") pub_date1,c.*,c.user_name MEMBER_NAME,(case  when c.end_date >= now() then 1 else 2 end) time_valid  from (
SELECT * from yl_tab c where 1=1 and c.is_delete='N' and c.USER_ID= '$_CRU_USER_ID_$' and valid=#{valid} 
<isNotEmpty property="TRUCK_SOURCE">  
  	and c.yl_source=#{TRUCK_SOURCE}
	</isNotEmpty>
	<isNotEmpty property="TRUCK_DEST">  
  	and c.destination=#{TRUCK_DEST}
	</isNotEmpty>
ORDER BY c.add_time desc 
) c  

</sql>
</mapper>

<!-- 获取在线车源详情 -->

<mapper id="getLineTruckInfoById">
	<sql key="getLineTruckInfoById" operator="select" resultType="map">
		SELECT  
	aa.*, cc.company_name,
if(aa.loc_way_from='2',aa.CONTACTS,if(bb.truck_id is null,ifnull(d.contact,aa.CONTACTS),aa.CONTACTS))  CONTACTS_NAME, 
if(aa.loc_way_from='2',aa.CONTACT_TEL,if(bb.truck_id is null,ifnull(d.contact_tel,aa.CONTACT_TEL),aa.CONTACT_TEL))  contacts_tel 
FROM 
	( 
		SELECT 
			DATE_FORMAT( 
				t.last_loc_time, 
				'%Y-%m-%d %T' 
			) LAST_LOC_TIME_FORMAT, 
			t.* 
		FROM 
			sys_truck_tab t 
		WHERE 
			1 = 1 and t.truck_id = #{TRUCK_ID} 
		) aa  left join truck_park_tab d on d.truck_plate=aa.TRUCK_PLATE  
left join (select a.truck_id from user_trucks_tab a   
inner join (select user_id from sys_user_tab where is_del='N' and effect=0) b on a.USER_ID=b.user_id  
GROUP BY a.truck_id) bb on aa.TRUCK_ID=bb.truck_id  
left join base_company_tab cc on aa.COMPANY_ID=cc.company_id
	</sql>
</mapper>

<!-- 获取用户企业信息 -->
<mapper id="getUserCompanyMsg">
	<sql key="getUserCompanyMsg" operator="select" resultType="map">
				select bct.*,sut.company_auth_status from (SELECT company_id,company_auth_status from sys_user_tab WHERE user_id='$_CRU_USER_ID_$' ) sut LEFT JOIN base_company_tab bct on sut.company_id=bct.company_id
   </sql>
</mapper>


<!-- 查询园区  -->
<mapper id="queryPark">
	<sql key="queryPark" operator="select" resultType="list">
		select PARK_ID,PARK_NAME from base_park_tab WHERE IS_DEL='N' and PARK_NAME!='' and PARK_NAME is NOT NULL and PARK_ID!='' and PARK_ID IS NOT NULL ORDER BY AREA_CODE DESC
</sql>
</mapper>

<!-- 根据code获取省市县text -->
<mapper id="getTextByCode">
    <sql key="getTextByCode" operator="select" resultType="map">
      SELECT group_concat(aa.TEXT) text FROM 
				(
					SELECT a.`CODE`,a.TEXT,a.PIN_YIN FROM base_area_tab a WHERE 1=1 
						UNION ALL 
					SELECT r.`CODE`,r.TEXT,r.PIN_YIN FROM region_divide_tab r WHERE 1=1 
				) aa WHERE 1=1 AND FIND_IN_SET(aa.`CODE`,#{CODE}) LIMIT 1 
    </sql>
</mapper>

<!-- 判断公司名是否存在 -->
<mapper id="checkCompanyName">
	<sql key="checkCompanyName" operator="select" resultType="map" >
		select COUNT(*) countCompany from base_company_tab where company_name=#{companyName} and company_id !=(select company_id from sys_user_tab WHERE user_id='$_CRU_USER_ID_$') 
</sql>
</mapper>

<!-- 我发布的货源-上下架操作 -->
<mapper id="setCargoIsShow">
	<sql key="setCargoIsShow"  operator="execute">
		update sys_cargo_tab set is_show=#{IS_SHOW}
			<isEqual property="IS_SHOW" compareValue="0">  
									,CREATE_TIME=now()
							</isEqual>
 where user_id=#{USER_ID} and seq=#{CARGO_ID} 
   </sql>
   <sql operator="callback" class="syncDelCargoCallBack" />
</mapper>

<!-- 删除我发布的货源 -->
<mapper id="deleteMyCargo">
	<sql key="deleteMyCargo"  operator="execute">
		update sys_cargo_tab set is_delete='Y' where user_id=#{USER_ID} and seq=#{CARGO_ID} 
   </sql>
   <sql operator="callback" class="syncDelCargoCallBack" />
</mapper>

<!-- 删除我发布的车源 -->
<mapper id="deleteMyTruck">
	<sql key="deleteMyTruck"  operator="execute">
		update yl_tab set is_delete='Y' where user_id=#{USER_ID} and yl_id=#{TRUCK_ID} 
   </sql>
</mapper>

<!-- 获取司机信息 -->
<mapper id="getDriverInfo">
	<sql key="getDriverInfo"  operator="select" resultType="map">
		select u.user_id,u.user_name,stt.TRUCK_PLATE,u.user_auth_status,ifnull(u.driver_type,0) driver_type 
		from 
			sys_user_tab u 
		LEFT JOIN sys_truck_tab stt on u.truck_id = stt.TRUCK_ID 
		where u.tel=#{driverTel} and u.is_del='N'
   </sql>
</mapper>

</mappers>
