=== huangtingliu/lanting/WebRoot/WEB-INF/sysxml/mappers.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.weimingfj.com/xsd/mappers" xmlns="http://www.weimingfj.com/xsd/mappers"
	elementFormDefault="qualified">
	<xsd:element name="isNotEmpty">
		<xsd:annotation>
			<xsd:documentation>
					<![CDATA[
					判断节点，property不为空的时候该节点的代码有效，null、""、属性不存在时候都为false
					可选，0个或者多个
					]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType mixed="true">
			<xsd:choice>
				<xsd:element ref="isNotEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isNotEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
			</xsd:choice>
			<xsd:attribute name="property" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>
							<![CDATA[
							必填，判断的属性名称
							]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="isEmpty">
		<xsd:annotation>
			<xsd:documentation>
					<![CDATA[
					判断节点，property为空的时候该节点的代码有效，null、""、属性不存在时候都为true
					可选，0个或者多个
					]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType mixed="true">
			<xsd:choice>
				<xsd:element ref="isNotEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isNotEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
			</xsd:choice>
			<xsd:attribute name="property" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>
						<![CDATA[
						必填，判断的属性名称
						]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="isEqual">
		<xsd:annotation>
			<xsd:documentation>
				<![CDATA[
				判断节点，比较property值为比较值或者比较属性值的时候有效;
				可以是属性和指定值比较，也可以属性和属性比较
				可选，0个或多个
				]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType mixed="true">
			<xsd:choice>
				<xsd:element ref="isNotEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isNotEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
			</xsd:choice>
			<xsd:attribute name="property" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>
						<![CDATA[
						必填，用户比较的属性
						]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="compareValue" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>
						<![CDATA[
						和compareProperty进行二选一，比较的值为固定值
						]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="compareProperty" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>
						<![CDATA[
						和compareValue进行二选一，不为空时候为属性和属性进行比较
						]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="isNotEqual" >
		<xsd:annotation>
			<xsd:documentation>
				<![CDATA[
				判断节点，比较property值不为比较值或者比较属性值的时候有效;
				可以是属性和指定值比较，也可以属性和属性比较
				可选，0个或多个
				]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType mixed="true">
			<xsd:choice>
				<xsd:element ref="isNotEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEmpty" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="isNotEqual" minOccurs="0" maxOccurs="unbounded"></xsd:element>
			</xsd:choice>
			<xsd:attribute name="property" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>
						<![CDATA[
						必填，用户比较的属性
						]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="compareValue" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>
						<![CDATA[
						和compareProperty进行二选一，比较的值为固定值
						]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="compareProperty" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>
						<![CDATA[
						和compareValue进行二选一，不为空时候为属性和属性进行比较
						]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="mappers">
		<xsd:annotation>
			<xsd:documentation>
				<![CDATA[
				单个逻辑执行语句，和url表一一映射，其中id和sys_url_tab，url_id字段一致
				]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="mapper" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>
							<![CDATA[
							单个逻辑执行语句，和url表一一映射，其中id和sys_url_tab，url_id字段一致
							]]>
						</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="sql" minOccurs="1" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>
										<![CDATA[
										执行的单条逻辑语句
										至少有一个
										]]>
									</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType mixed="true">
									<xsd:choice minOccurs="0" maxOccurs="unbounded">
										<xsd:element ref="isNotEmpty"></xsd:element>
										<xsd:element ref="isEmpty"></xsd:element>
										<xsd:element ref="isNotEqual"></xsd:element>
										<xsd:element ref="isEqual"></xsd:element>
									</xsd:choice>
									<xsd:attribute name="key" type="xsd:string">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
												可选，sql在当前mapper中唯一
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="dynamic" default="false"
										type="xsd:boolean">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
												动态分页查询查询语句，queryService有效，默认为false，为true代表获取的数据分页量由用户自主控制
												否则系统会跟踪数据库类型进行分页语句的拼装
												可选
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="resultType" default="list">
										<xsd:annotation>
											<xsd:documentation>    
												<![CDATA[
												查询返回类型，ajaxService有效， list/map/string/page；四个操作,默认为list
												list 代表返回list
												map 代表返回map
												string 代表返回String
												page 返回分页对象 paginForm
												]]>
											</xsd:documentation>
										</xsd:annotation>
										<xsd:simpleType>
											<xsd:restriction base="xsd:NMTOKEN">
												<xsd:enumeration value="list" />
												<xsd:enumeration value="map" />
												<xsd:enumeration value="string" />
												<xsd:enumeration value="page" />
											</xsd:restriction>
										</xsd:simpleType>
									</xsd:attribute>
									<xsd:attribute name="operator" default="execute">
										<xsd:annotation>
											<xsd:documentation>    
												<![CDATA[
												sql操作类型，值为select/insert_file/del_file/execute/callback；五个操作,默认为execute
												execute 代表执行sql语句
												select 代表执行查询语句
												insert_file 代表插入文件
												del_file 代表删除文件
												callback 代表回调方法
												]]>
											</xsd:documentation>
										</xsd:annotation>
										<xsd:simpleType>
											<xsd:restriction base="xsd:NMTOKEN">
												<xsd:enumeration value="execute" />
												<xsd:enumeration value="select" />
												<xsd:enumeration value="insert_file" />
												<xsd:enumeration value="del_file" />
												<xsd:enumeration value="callback" />
											</xsd:restriction>
										</xsd:simpleType>
									</xsd:attribute>
									<xsd:attribute name="class" type="xsd:string">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
												可选，用于opertor为callbak回调适用的类
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="iterfields" default=""
										type="xsd:string">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
													可选，需要迭代执行的字段，用了这个属性，根据实际情况会产生多条执行语句；
													比如页面是主订单和字订单时，子订单有多条，实际情况是保存了主订单，还需要保存子订单（多条）
													可以用到该字段，比如子订单的字段分别有sub_order_id、sub_order_no、sub_order_name等
													这里的字段就填写成sub_order_id,sub_order_no,sub_order_name
													注：和iterfieldsplit有关系，当iterfieldsplit不为空试试，按照页面提交的值进行分割生成迭代语句
													当iterfieldsplit为空，则按照网页上提交的参数个数生成迭代语句
													operator=execute时候有效
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="iterfieldsplit" default=""
										type="xsd:string">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
													可选，和iterfields配合使用
													当这个字段不为空时，需要迭代属性值（迭代的属性参考字段iterfields）就按照这个字符串进行分割
													如iterfields=rights,name，iterFieldSplit=“---”
													页面提交的参数rights=101---102name=101name---102name，迭代的次数为2
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="filewname" default="_FILE_"
										type="xsd:string">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
													可选，有附件上传的时候使用，不存在该属性时，值为_FILE_；
													为网页上的附件控件（如  <input type="file" name="_FILE_">;）
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="fileindex" default=""
										type="xsd:string">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
												可选，配合filewname使用，默认为空，为多类附件上传的时候使用，如头像上传、身份证上传
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="id" type="xsd:string">
							<xsd:annotation>
								<xsd:documentation>
									<![CDATA[
									唯一值，和url表一一映射，其中id和sys_url_tab，url_id字段一致
									]]>
								</xsd:documentation>
							</xsd:annotation>
						</xsd:attribute>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== huangtingliu/lanting/WebRoot/WEB-INF/sysxml/execsql/credit.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappers xmlns="http://www.weimingfj.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://itest.56913.com:20080/xsd/mappers.xsd">
<!-- 我的贷款状态 -->
<mapper id="getCreditStatus">
	<sql key="getCreditStatus" resultType="map" operator="select">
				SELECT mpot.CREATE_USER,mpot.STATE,mpot.LOAN_SUCCESS,mcot.CHG_DESC from ms_personal_order_tab mpot 
			left join  ms_order_chg_tab mcot on mpot.ORDER_ID=mcot.ORDER_ID and mpot.STATE=mcot.STATE 
where mpot.CREATE_USER="$_CRU_USER_ID_$" and mpot.is_effect ="Y" 
   </sql>
</mapper>
<mapper id="getPersonalCredit">
	<sql key="getPersonalCredit" resultType="map" operator="select">
				SELECT mpot.*,bat.full_text areacode_text,bat1.full_text census_area_text from ms_personal_order_tab mpot 
				left join base_area_tab bat on mpot.areacode=bat.CODE 
				left join base_area_tab bat1 on mpot.census_area = bat1.CODE 
where mpot.CREATE_USER="$_CRU_USER_ID_$" and mpot.is_effect ="Y" GROUP BY mpot.CREATE_USER
   </sql>
</mapper>
<!-- 个人贷款申请 -->
<mapper id="savePersonalCredit">
<sql key="savePersonalCredit"  operator="execute">
	update ms_personal_order_tab set is_effect='N' where CREATE_USER='$_CRU_USER_ID_$' and LOAN_SUCCESS!='D'
</sql>
	<sql key="savePersonalCredit1"  operator="execute">
					INSERT into ms_personal_order_tab(ORDER_ID,PROPOSER_TYPE,NAME,SEX,BIRTHDAY,NATIONALITY,NATION,MARITAL,CERT_TYPE,CERT_NO,HOME_PHONE,MOBILE,CENSUS_TYPE,CENSUS_AREA,FUND_INFO,CENSUS_ADDR,
CORP_NAME,BUSINESS,REG_DATE,AREACODE,ADDR,REG_CAPITAL,REG_CAPITAL_UNIT,REAL_CAPITAL,REAL_CAPITAL_UNIT,CORP_MEMBER,CTRL_MEMBER,CTRL_MEMBER_TIME,CONTACT_PHONE,MEMBERS,OFFICE_GET,LAST_DEBTS,LAST_FUND,CURR_FUND,
CURR_SALES,LAST_SALES,CURR_ASSETS,CURR_DEBTS,DEBTS_DETAILS,LOAN_AMOUNT,APP_TIME,STATE,ORDER_TYPE,PROPOSER,PROPOSER_TEL,ORDER_CODE,CREATE_USER)
values (#{order_id},#{PROPOSER_TYPE},#{name},#{SEX},#{birthday},#{nationality},#{nation},#{MARITAL},#{CERT_TYPE},#{cert_no},#{home_phone},#{mobile},#{CENSUS_TYPE},#{census_area},#{fund_info},#{census_addr},
#{corp_name},#{business},#{reg_date},#{areacode},#{addr},#{reg_capital},#{reg_capital_unit},#{real_capital},#{real_capital_unit},#{corp_member},#{ctrl_member},#{ctrl_member_time},#{contact_phone},
#{members},#{OFFICE_GET},#{last_debts},#{last_fund},#{curr_fund},
#{curr_sales},#{last_sales},#{curr_assets},#{curr_debts},#{debts_details},#{loan_amount},now(),#{state},#{order_type_txt},'$_CRU_USER_NAME_$',#{userMobile},date_format(now(),"%Y%m%d%h%i%s%f"),'$_CRU_USER_ID_$')
   </sql>
</mapper> 
<!-- 企业贷款申请 -->
<mapper id="saveCompanyCredit">
<sql key="saveCompanyCredit"  operator="execute">
	update ms_personal_order_tab set is_effect='N' where CREATE_USER='$_CRU_USER_ID_$' and LOAN_SUCCESS!='D' 
</sql>
	<sql key="saveCompanyCredit1"  operator="execute">
					INSERT into ms_personal_order_tab(ORDER_ID,CORP_NAME,BUSINESS,REG_DATE,AREACODE,ADDR,REG_CAPITAL,REG_CAPITAL_UNIT,REAL_CAPITAL,REAL_CAPITAL_UNIT,CORP_MEMBER,CTRL_MEMBER,CTRL_MEMBER_TIME,CONTACT_PHONE,MEMBERS,OFFICE_GET,LAST_DEBTS,LAST_FUND,CURR_FUND,
CURR_SALES,LAST_SALES,CURR_ASSETS,CURR_DEBTS,DEBTS_DETAILS,LOAN_AMOUNT,APP_TIME,STATE,ORDER_TYPE,PROPOSER,PROPOSER_TEL,ORDER_CODE,CREATE_USER)
values (#{order_id},#{corp_name},#{business},#{reg_date},#{areacode},#{addr},#{reg_capital},#{reg_capital_unit},#{real_capital},#{real_capital_unit},#{corp_member},#{ctrl_member},#{ctrl_member_time},#{contact_phone},
#{members},#{COMP_OFFICE_GET},#{last_debts},#{last_fund},#{curr_fund},
#{curr_sales},#{last_sales},#{curr_assets},#{curr_debts},#{debts_details},#{loan_amount},now(),#{state},#{order_type_txt},'$_CRU_USER_NAME_$',#{userMobile},DATE_FORMAT(now(),"%Y%m%d%h%i%s%f"),'$_CRU_USER_ID_$')
   </sql>
</mapper> 
<!-- 个人贷款修改 -->
<mapper id="updatePersonalCredit">
	<sql key="updatePersonalCredit"  operator="execute">
update ms_personal_order_tab SET PROPOSER_TYPE=#{PROPOSER_TYPE},NAME=#{name},SEX=#{SEX},BIRTHDAY=#{birthday},NATIONALITY=#{nationality},NATION=#{nation},MARITAL=#{MARITAL},CERT_TYPE=#{CERT_TYPE},CERT_NO=#{cert_no}
,HOME_PHONE=#{home_phone},MOBILE=#{mobile},CENSUS_TYPE=#{CENSUS_TYPE},CENSUS_AREA=#{census_area},FUND_INFO=#{fund_info},CENSUS_ADDR=#{census_addr},CORP_NAME=#{corp_name},BUSINESS=#{business},REG_DATE=#{reg_date}
,AREACODE=#{areacode},ADDR=#{addr},REG_CAPITAL=#{reg_capital},REG_CAPITAL_UNIT=#{reg_capital_unit},REAL_CAPITAL=#{real_capital},REAL_CAPITAL_UNIT=#{real_capital_unit},CORP_MEMBER=#{corp_member},CTRL_MEMBER=#{ctrl_member}
,CTRL_MEMBER_TIME=#{ctrl_member_time},CONTACT_PHONE=#{contact_phone},OFFICE_GET=#{OFFICE_GET},LAST_DEBTS=#{last_debts},LAST_FUND=#{last_fund},CURR_FUND=#{curr_fund},CURR_SALES=#{curr_sales},LAST_SALES=#{last_sales}
,CURR_ASSETS=#{curr_assets},CURR_DEBTS=#{curr_debts},DEBTS_DETAILS=#{debts_details},LOAN_AMOUNT=#{loan_amount},ORDER_TYPE=#{order_type_txt},STATE=#{state},members=#{members} 
WHERE ORDER_ID=#{order_id}
   </sql>
</mapper> 
<!-- 企业贷款修改 -->
<mapper id="updateCompanyCredit">
	<sql key="updateCompanyCredit"  operator="execute">
update ms_personal_order_tab SET CORP_NAME=#{corp_name},BUSINESS=#{business},REG_DATE=#{reg_date}
,AREACODE=#{areacode},ADDR=#{addr},REG_CAPITAL=#{reg_capital},REG_CAPITAL_UNIT=#{reg_capital_unit},REAL_CAPITAL=#{real_capital},REAL_CAPITAL_UNIT=#{real_capital_unit},CORP_MEMBER=#{corp_member},CTRL_MEMBER=#{ctrl_member}
,CTRL_MEMBER_TIME=#{ctrl_member_time},CONTACT_PHONE=#{contact_phone},OFFICE_GET=#{COMP_OFFICE_GET},LAST_DEBTS=#{last_debts},LAST_FUND=#{last_fund},CURR_FUND=#{curr_fund},CURR_SALES=#{curr_sales},LAST_SALES=#{last_sales}
,CURR_ASSETS=#{curr_assets},CURR_DEBTS=#{curr_debts},DEBTS_DETAILS=#{debts_details},LOAN_AMOUNT=#{loan_amount},ORDER_TYPE=#{order_type_txt},STATE=#{state},members=#{members} 
WHERE ORDER_ID=#{order_id}
   </sql>
</mapper> 
<!-- 获取贷款详情 -->
<mapper id="toPersonalCreditDetail">
	<sql key="toPersonalCreditDetail" operator="select" resultType="list"> 
select moct.auth_user,moct.auth_user_tel,moct.CHG_DESC,DATE_FORMAT(moct.FEED_TIME,"%Y-%m-%d") FEED_TIME,sdt.text STATE,(case when mpot.state=moct.state then mpot.LOAN_SUCCESS else 'D' end )LOAN_SUCCESS from ms_personal_order_tab mpot left join ms_order_chg_tab moct on mpot.order_id = moct.order_id 
				left join sys_dict_tab sdt on moct.state=sdt.code and sdt.type='ORDER_STATE'
				where mpot.CREATE_USER='$_CRU_USER_ID_$' and mpot.is_effect='Y' and mpot.state!='1' and  mpot.state!='2'  ORDER BY moct.STATE
   </sql>
</mapper>
</mappers>

=== huangtingliu/lanting/WebRoot/WEB-INF/sysxml/execsql/zxcc.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappers xmlns="http://www.weimingfj.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://itest.56913.com:20080/xsd/mappers.xsd">
	<mapper id="load_line_truck_info">
		<sql key="load_line_truck_info" operator="select" resultType="paging">
			SELECT <isNotEmpty property="query_count"> count(1) </isNotEmpty>
<isEmpty property="query_count">
DISTINCT(CONCAT_WS('',aa.TRUCK_PLATE, aa.TRUCK_PLATE_COLOR)) as d,
aa.DRIVER_NAME,aa.DRIVER_TEL,
if(aa.loc_way_from='2',aa.CONTACTS,if(bb_truck_id is null,ifnull(d.contact,aa.CONTACTS),aa.CONTACTS)) CONTACTS,
if(aa.loc_way_from='2',aa.CONTACT_TEL,if(bb_truck_id is null,ifnull(d.contact_tel,aa.CONTACT_TEL),aa.CONTACT_TEL)) contact_tel,
aa.LAST_LOC_ADDR,aa.LAST_LOC_TIME_FORMAT,aa.OFTEN_RUN_AREA,aa.LOC_WAY_FROM,aa.WAY_FROM,
aa.LAST_LOC_LNG,aa.LAST_LOC_LAT,aa.TRUCK_ID,aa.truck_type,aa.truck_length,aa.TRUCK_TON,aa.TRUCK_PLATE,aa.TRUCK_PLATE_COLOR,
yl.yl_id,yl.YL_SOURCE,yl.DESTINATION,DATE_FORMAT(yl.END_DATE,'%Y-%m-%d') END_DATE,DATE_FORMAT(yl.START_DATE,'%Y-%m-%d') START_DATE,yl.YL_DATE,( select  count(1) from collect where 1=1 and member_id='$_CRU_USER_ID_$' 
and collect_type=3 and collect_id=aa.TRUCK_ID ) as TYPE,if(is_vip='1','1','0') viptype,
(select count(1) from yb_vip_user_today_his yvut where yvut.userid='$_CRU_USER_ID_$' and yvut.code='ZXCC' and yvut.object_id=aa.TRUCK_ID and source='WEB') isshow   
FROM (
SELECT 	DATE_FORMAT(tt.LAST_LOC_TIME,'%m-%d %H:%i') LAST_LOC_TIME_FORMAT,
			tt.LAST_LOC_TIME, 
			tt.TRUCK_PLATE,
			tt.TRUCK_PLATE_COLOR,
			tt.TRUCK_ID,
			tt.DRIVER_NAME,
			tt.DRIVER_TEL,
			tt.LOC_WAY_FROM,
			tt.CONTACTS,
			tt.CONTACT_TEL,
			tt.LAST_LOC_ADDR,bb.truck_id bb_truck_id,
			if(vip.userid is null,'0','1') is_vip,
tt.OFTEN_RUN_AREA,tt.WAY_FROM,tt.LAST_LOC_LNG,tt.LAST_LOC_LAT,tt.TRUCK_TYPE,tt.TRUCK_LENGTH,tt.TRUCK_TON 
</isEmpty>
FROM `sys_truck_tab` tt 
left join sys_user_tab bb on tt.DRIVER_TEL = bb.tel and bb.is_del = 'N'
LEFT JOIN(SELECT userid FROM sys_user_vip WHERE vip_type IN(1, 2) GROUP BY userid )vip ON vip.userid = bb.user_id 
WHERE tt.is_delete!=1 and tt.WAY_FROM !='0' and
 (tt.AUTH_STATUS='2' or (tt.AUTH_STATUS='0' and <![CDATA[ timestampdiff(hour,tt.LAST_LOC_TIME, now()) < 24 ]]>) )
	AND tt.LAST_LOC_LNG IS NOT NULL  
	AND tt.LAST_LOC_LAT IS NOT NULL 
	AND tt.LAST_LOC_ADDR is not null  and tt.LAST_LOC_ADDR !=''  
	<isNotEmpty property="vip_type">  
	<isEqual property="vip_type" compareValue="1"> 
	   and bb.is_vip = '1'   
	</isEqual>
	<isEqual property="vip_type" compareValue="0"> 
	  and  (bb.is_vip is null or bb.is_vip='0') 
	</isEqual>
</isNotEmpty>
	<isNotEmpty property="purpose">  
  	AND tt.LAST_LOC_ADDR LIKE '%${purpose}%' 
	</isNotEmpty>
	<isNotEmpty property="phone">  
  	AND tt.CONTACT_TEL LIKE '%${phone}%' 
	</isNotEmpty>
	<isNotEmpty property="prov">  
  	AND tt.LAST_LOC_ADDR LIKE '${prov}%' 
	</isNotEmpty>
<isNotEmpty property="city">  
  	AND tt.LAST_LOC_ADDR LIKE '%${city}%' 
	</isNotEmpty>
<isNotEmpty property="town">  
  	AND tt.LAST_LOC_ADDR LIKE '%${town}%' 
	</isNotEmpty>
	<isNotEmpty property="prov1">  
  	AND tt.TRUCK_PLATE LIKE 
  		CONCAT('%',( SELECT 
  		<isNotEmpty property="isOnlyProv">
  			 DISTINCT LEFT(SCAT.CP_NAME,1)  
  		 </isNotEmpty>
  		 <isEmpty property="isOnlyProv">
  		 	SCAT.CP_NAME 
  		 </isEmpty>
  		 FROM sys_cp_area_tab SCAT 
  		 WHERE  SCAT.PROVINCE LIKE '%${prov1}%' 
  		 <isNotEmpty property="city1"> 
  		 AND SCAT.CITY LIKE '%${city1}%' 
  		 </isNotEmpty>
  		 ),'%')  
	</isNotEmpty>
	<isNotEmpty property="WAY_FROM">  
  	AND tt.LOC_WAY_FROM IN (${WAY_FROM}) 
	</isNotEmpty>
	<isNotEmpty property="TRUCK_PLATE">  
  	AND tt.TRUCK_PLATE LIKE '%${TRUCK_PLATE}%' 
	</isNotEmpty>
	
	<isNotEmpty property="TRUCK_LENGTH">  
  	AND tt.TRUCK_LENGTH = '${TRUCK_LENGTH}' 
	</isNotEmpty>
<isNotEmpty property="TRUCK_LOAD">  
  	AND tt.TRUCK_TON = '${TRUCK_LOAD}' 
	</isNotEmpty>
<isNotEmpty property="TRUCK_TYPE">  
  	AND tt.TRUCK_TYPE = '${TRUCK_TYPE}' 
	</isNotEmpty>
<isEmpty property="query_count">
	ORDER BY tt.LAST_LOC_TIME DESC  
  LIMIT  ${PAGESTART}, ${PAGENUM} 
</isEmpty>
<isEmpty property="query_count">
	) aa 
LEFT JOIN (select t.TRUCK_PLATE,
		t.TRUCK_PLATE_COLOR,
		t.YL_ID,
		t.YL_SOURCE,
		t.DESTINATION,
		t.END_DATE,
	t.START_DATE,
t.YL_DATE  from(select TRUCK_PLATE,MAX(t.ADD_TIME) ADD_TIME from yl_tab t where t.IS_DELETE='N' and VALID=1 and t.end_date >= now() and t.TRUCK_PLATE is not null and t.TRUCK_PLATE!=''GROUP by TRUCK_PLATE) a  	  left join yl_tab t on a.TRUCK_PLATE=t.TRUCK_PLATE and a.ADD_TIME=t.ADD_TIME) yl on aa.TRUCK_PLATE=yl.TRUCK_PLATE and aa.TRUCK_PLATE_COLOR=yl.TRUCK_PLATE_COLOR 
left join truck_park_tab d on d.truck_plate=aa.TRUCK_PLATE   
ORDER BY aa.LAST_LOC_TIME DESC 
</isEmpty>
		</sql>
	</mapper>
	
	<mapper id="select_all_prov">
  <sql key="select_all_prov"  resultType="list" operator="select">
		select DISTINCT province, SUBSTR(cp_name,1,1) cp_name  from sys_cp_area_tab   order by pin_yin
	</sql>
</mapper>

<mapper id="select_all_city">
  <sql key="select_all_city" resultType="list" operator="select">
		select city,  cp_name  from sys_cp_area_tab sc  where province='${P_NAME}' order by pin_yin
	</sql>
</mapper>
</mappers>

=== huangtingliu/lanting/WebRoot/WEB-INF/sysxml/execsql/wx.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappers xmlns="http://www.weimingfj.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://itest.56913.com:20080/xsd/mappers.xsd">
	<!-- 微信端-司机认证添加 -->
	<mapper id="uploadDriverAudit">
		<sql id="uploadDriverAudit" operator="execute">
		    insert into auth_personal_tab (user_id,apply_source,apply_date,status,real_name,id_no,id_card_front,driver_lic_photo,type,phone)values
		    ('$_CRU_USER_ID_$','8',now(),'D',#{real_name},#{id_no},#{id_card_front_f},#{driver_lic_photo_f},'2',#{tel})
		</sql>	
		<sql id="updateUserStatus" operator="execute">
		    update sys_user_tab set user_auth_status='D' where user_id='$_CRU_USER_ID_$'
		</sql>    
	</mapper>
	<!-- 微信端-企业认证添加 -->
	<mapper id="uploadCompanyAudit">
		<sql id="uploadCompanyAudit" operator="execute">
		    insert into auth_company_tab (user_id,apply_source,apply_date,status,company_name,operate_lic_path,shop_photo_path)values
		    ('$_CRU_USER_ID_$','8',now(),'D',#{company_name},#{operate_lic_path_f},#{driver_lic_photo_f})
		</sql>
		<sql id="uploadUserAudit" operator="execute">
				insert into auth_personal_tab (user_id,apply_source,apply_date,status,real_name,id_card_front,phone)values
		    	('$_CRU_USER_ID_$','8',now(),'D',#{real_name},#{id_card_front_f},#{tel}) 
		</sql>
		<sql id="uploadUserAuditStatus" operator="execute">
		    update sys_user_tab set user_auth_status='D' where user_id='$_CRU_USER_ID_$'
		</sql>
		<sql id="updateCompanyStatus" operator="execute">
		    update sys_user_tab set company_auth_status='D' where user_id='$_CRU_USER_ID_$'
		</sql>    
	</mapper>
	<!-- 微信端-参与活动 -->
	<mapper id="enterAct">
		<sql id="enterAct" operator="execute">
		    insert into activity_201509_old_new (new_mobile,old_user_id,status,join_date) values 
		    (#{new_mobile},#{old_user_id},'0',now())
		</sql>	
	</mapper>
	<!-- 微信端-用户注册 -->
	<mapper id="registerForWX">
	    <sql id="registerForWX" operator="execute">
	        insert into sys_user_tab(user_id,user_pwd,user_code,tel,create_date,user_type) values 
	        (#{user_id},SUBSTR(MD5(#{user_pwd}) FROM 9 FOR 16),#{user_code},#{tel},now(),'10')
	    </sql>
	</mapper>
	<mapper id="queryExpress">
		<sql key="queryExpress" operator="select" resultType="list" >  
			select * from sys_express_tab where is_del='N'  		 
	  	</sql>
	</mapper>
</mappers>

=== huangtingliu/lanting/WebRoot/WEB-INF/sysxml/execsql/report.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappers xmlns="http://www.weimingfj.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://itest.56913.com:20080/xsd/mappers.xsd">
	
	<mapper id="exportReportList">
	    <sql key="exportReportList" operator="select" resultType="list">
	    	SELECT
				t1.order_no,
				t3.company,
				t1.loading_addr,
				t1.receive_addr,
				t2.user_name driver_name,
				if(t1.way_length like '%里%',t1.way_length,concat(t1.way_length,'km'))way_length,
				concat(
					IF (
						HOUR (
							TIMEDIFF(arrive_date, pick_date)
						) > 0,
						concat(
							HOUR (
								TIMEDIFF(arrive_date, pick_date)
							),
							'时'
						),
						''
					),
					IF (
						MINUTE (
							TIMEDIFF(arrive_date, pick_date)
						) > 0,
						concat(
							MINUTE (
								TIMEDIFF(arrive_date, pick_date)
							),
							'分'
						),
						''
					),
					IF (
						SECOND (
							TIMEDIFF(arrive_date, pick_date)
						) > 0,
						concat(
							SECOND (
								TIMEDIFF(arrive_date, pick_date)
							),
							'秒'
						),
						''
					)
				) pay_time,
				CASE order_status
			WHEN '3' THEN
				'进行中'
			WHEN '6' THEN
				'结束'
			ELSE
				''
			END order_status,
			 date_format(pick_date, '%Y.%m.%d %H:%i') pick_date,
			 date_format(
				arrive_date,
				'%Y.%m.%d %H:%i'
			) arrive_date,
			 case when fee is null or fee='' then '面议' else  fee end fee,
			 remark,
			
			IF (
				driver_sign_name_pic IS NULL
				OR driver_sign_name_pic = '',
				'否',
				'是'
			) is_order_back
			FROM
				transport_order_cargouser_tab t1
			LEFT JOIN sys_user_tab t2 ON t1.driver_id = t2.user_id
			LEFT JOIN sys_user_tab t3 ON t1.create_user_id = t3.user_id
			WHERE
				t1.order_status IN ('3', '6') AND t2.is_del = 'N'
			<isNotEmpty property="order_no">
				and t1.order_no like '%${order_no}%'
			</isNotEmpty>
			<isNotEmpty property="start_area">
				and t1.loading_addr like '%${start_area}%'
			</isNotEmpty>
			<isNotEmpty property="end_area">
				and t1.receive_addr like '%${end_area}%'
			</isNotEmpty>
			<isNotEmpty property="place_from_code">
				and loading_code like  '${place_from_code}%'
			</isNotEmpty>
			<isNotEmpty property="place_to_code">
				and receive_code like  '${place_to_code}%'
			</isNotEmpty>
			<isNotEmpty property="driver_name">
				and t2.user_name like '%${driver_name}%'
			</isNotEmpty>
			<isNotEmpty property="company_name">
				and t3.company like '%${company_name}%'
			</isNotEmpty>
			<isNotEmpty property="start_time_begin">
				and  t1.pick_date>= concat(#{start_time_begin},' 00:00:00')
			</isNotEmpty>
			<isNotEmpty property="start_time_end">
				and  t1.pick_date &lt;= concat(#{start_time_end},' 23:59:59')
			</isNotEmpty>
			<isNotEmpty property="end_time_begin">
				and  t1.arrive_date>= concat(#{end_time_begin},' 00:00:00')
			</isNotEmpty>
			<isNotEmpty property="end_time_end">
				and  t1.arrive_date &lt;= concat(#{end_time_end},' 23:59:59')
			</isNotEmpty>
			ORDER BY
				t1.pick_date DESC
	    	
		</sql>
	</mapper>

	<!-- 获取报表图表统计数据 -->
	<mapper id="getReportData">
		<sql operator="select" resultType="list">
			SELECT
				yyyymm,
				mm,
				count(0) cargoCnt,
			 sum(a.conver) conver
			FROM
				(
					SELECT 
						DATE_FORMAT(c.CREATE_TIME, '%Y年%m月') yyyymm,
						month(c.CREATE_TIME) mm,
						if(t.order_status='3'||t.order_status='6',1,0) conver
					FROM
						sys_cargo_tab c 
					LEFT JOIN transport_order_cargouser_tab t on c.SEQ  = t.cargo_id 
					WHERE
						<isEmpty property="year">
						c.CREATE_TIME BETWEEN '2016-01-01 00:00:00' and '2016-12-31 23:59:59'
						</isEmpty>
						<isNotEmpty property="year">
						c.CREATE_TIME BETWEEN concat(#{year},'-01-01 00:00:00') and concat(#{year},'-12-31 23:59:59')
						</isNotEmpty>
				) a
			
			GROUP BY
			 	yyyymm
			ORDER BY
				yyyymm
		</sql>
	</mapper>
</mappers>
