=== huangtingliu/lanting/WebRoot/WEB-INF/sysxml/validations.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.weimingfj.com/xsd/validations" xmlns="http://www.weimingfj.com/xsd/validations"
	elementFormDefault="qualified">
	<xsd:element name="validations">   
		<xsd:annotation>
			<xsd:documentation>
				<![CDATA[
				后台表单业务验证
				]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="validation" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>
							<![CDATA[
							验证的属性，可以是正则表达式，也可以是执行sql
							]]>
						</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="property" minOccurs="1" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>
										<![CDATA[
										待验证的表单属性节点
										]]>
									</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType >
									<xsd:attribute name="field" type="xsd:string"
										use="required">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
												必填，待验证的属性名称
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="method" default="reg" use="optional">
										<xsd:annotation>
											<xsd:documentation>    
												<![CDATA[
												验证方法，待选项有reg和database和class
												reg，使用正则表达式，reg属性不能为空
												database，使用数据库验证方式，sql属性不能为空
												class,适用类验证
												]]>
											</xsd:documentation>
										</xsd:annotation>
										<xsd:simpleType>
											<xsd:restriction base="xsd:NMTOKEN">
												<xsd:enumeration value="reg" />
												<xsd:enumeration value="database" />
												<xsd:enumeration value="class" />
											</xsd:restriction>
										</xsd:simpleType>
									</xsd:attribute>
									<xsd:attribute name="required" type="xsd:boolean"
										default="true">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
												该字段是否不能为空，默认为true
												可选
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="reg" default="">
										<xsd:annotation>
											<xsd:documentation>    
												<![CDATA[
												和method=reg配合使用，正则表示式
												 *			required : 非空，表单值至少要有一个非空格，制表符，换行符
												 *			email : 邮件
												 *			phone : 电话号码
												 *			mobile : 手机号码
												 *			url : url地址
												 *			idcard :身份证
												 *			currency : 日期  
												 *			posiint : 正整数
												 *			number : 数字
												 *			zip : 邮政信箱   
												 *			qq : qq号码
												 *			integer : 整数 
												 *			double : 浮点数
												 *			posi_float : 正浮点数
												 *			no_negative_float : 不小于浮点数
												 *			posi_number : 正数(可以带小数点)
												 *			english : 英文字母
												 *			barcode : 英文字母+汉字
												 *			chinese : 汉字
												 *			unsafe : 
												 *			allphone:所有电话
												 *			ipaddr:ip地址
												"required" : /^[\s\S]*\S[\s\S]*$/,
												"email" : /^\w+((-\w+)|(\.\w+))*\@[A-Za-z0-9]+((\.|-)[A-Za-z0-9]+)*\.[A-Za-z0-9]+$/,
												"phone" : /^((\(\d{3}\))|(\d{3}\-))?(\(0\d{2,3}\)|0\d{2,3}-)?[1-9]\d{6,7}$/,
												"mobile" : /^((\(\d{3}\))|(\d{3}\-))?13\d{9}$/,
												"url" : /^http:\/\/[A-Za-z0-9]+\.[A-Za-z0-9]+[\/=\?%\-&_~`@[\]\':+!]*([^<>\"\"])*$/,
												"idcard" : /^\d{15}(\d{2}[A-Za-z0-9])?$/,
												"currency":/^(\d{4})\-(\d{2})\-(\d{2})$/, 
												"posiint":/^[0-9]*[1-9][0-9]*$/,
												"number" : /^\d+$/,
												"zip" : /^[1-9]\d{5}$/,
												"qq" : /^[1-9]\d{4,8}$/,
												"integer" : /^[-\+]?\d+$/,
												"double" : /^(-|((-?\d+)(\.\d+)?)|(-?\d+)\.)$/,
												"posi_float":/^(([0-9]+\.[0-9]*[1-9][0-9]*)|([0-9]*[1-9][0-9]*\.[0-9]+)|([0-9]*[1-9][0-9]*))$/,
												"no_negative_float":/^(([0-9]+\.[0-9]*[0-9][0-9]*)|([0-9]*[0-9][0-9]*\.[0-9]+)|([0-9]*[0-9][0-9]*))$/,
												"posi_number":/^[0-9]+[.][0-9]{0,3}$/,
												"english" : /^[A-Za-z]+$/,
												"barcode":/^[A-Za-z0-9]+$/,
												"chinese" : /^[\u0391-\uFFE5]+$/,
												"unsafe" : /^(([A-Z]*|[a-z]*|\d*|[-_\~!@#\$%\^&\*\.\(\)\[\]\{\}<>\?\\\/\'\"]*)|.{0,5})$|\s/,
												"allphone" : /^(\d{3,4}\)|\d{3,4}-|\s)?\d{7,14}/,
												"ipaddr" : /^([1-9]|[1-9]\d|1\d{2}|2[0-1]\d|22[0-3])(\.(\d|[1-9]\d|1\d{2}|2[0-4]\d|25[0-5])){3}$/
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="sql" default="">
										<xsd:annotation>
											<xsd:documentation>    
												<![CDATA[
												和method=database配合使用，待验证的sql
												sql必须只返回一个值，0和1，如果不为0代表验证不通过，为0代表验证通过
												例如：select count(1) from sys_user_tab where code=#{code,string} and user_id!=#{userid,int}
												可选
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="class" type="xsd:string">
										<xsd:annotation>
											<xsd:documentation>
												<![CDATA[
												可选，用于method为class时类名标识
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="msg" default="">
										<xsd:annotation>
											<xsd:documentation>    
												<![CDATA[
												验证不通过的时候，提示给用户的信息
												如：姓名不能为空
												可选
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="maxlength" type="xsd:int">
										<xsd:annotation>
											<xsd:documentation>    
												<![CDATA[
												字段的最大长度
												method=reg,该字段有效
												可选
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
									<xsd:attribute name="minlength" type="xsd:int">
										<xsd:annotation>
											<xsd:documentation>    
												<![CDATA[
												字段的最小长度
												method=reg,该字段有效
												可选
												]]>
											</xsd:documentation>
										</xsd:annotation>
									</xsd:attribute>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="id" type="xsd:string">
							<xsd:annotation>
								<xsd:documentation>
									<![CDATA[
									唯一值，和url表一一映射，其中id和sys_url_tab，url_id字段一致
									]]>
								</xsd:documentation>
							</xsd:annotation>
						</xsd:attribute>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== huangtingliu/lanting/WebRoot/WEB-INF/sysxml/validation/sys.xml
<?xml version="1.0" encoding="UTF-8"?>
<validations xmlns="http://www.weimingfj.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://itest.56913.com:20080/xsd/validations.xsd">
	<!-- 删除部门是查找是否还有下级部门 -->
    <validation id="delDept" >
		<property field="DEPT_ID" method="database" msg="该部门底下包含子部门,无法进行删除!" sql="select count(1) from cp_dept_tab where F_DEPT_ID=${DEPT_ID} and IS_DEL='N' " ></property>
	</validation>
	<!-- 保存时判断部门名是否存在 -->
    <validation id="saveDept">
		<property field="DEPT_NAME" method="database" msg="该名称已被使用, 请重新输入!" sql="select count(1) from cp_dept_tab where cp_id=#{session_company_id} and IS_DEL='N' and DEPT_NAME=#{DEPT_NAME}" ></property>
	</validation>
	<!-- 修改时判断部门名是否存在 -->
    <validation id="editDept">
		<property field="DEPT_NAME" method="database" msg="该名称已被使用, 请重新输入!" sql="select count(1) from cp_dept_tab where DEPT_ID!=${DEPT_ID} and IS_DEL='N' and cp_id=#{session_company_id} and DEPT_NAME=#{DEPT_NAME}" ></property>
	</validation>
    <!-- 保存角色时判断角色名是否存在 -->
    <validation id="saveRole">
		<property field="ROLE_NAME" method="database" msg="角色名称必须唯一" sql="select count(1) from cp_role_tab where is_del='N' and cp_id=#{session_company_id} and ROLE_NAME=#{ROLE_NAME}" ></property>
	</validation>
    <!-- 编辑角色时判断角色名是否存在 -->
    <validation id="editRole">
		<property field="ROLE_NAME" method="database" msg="角色名称已存在" sql="select count(1) from cp_role_tab where ROLE_NAME=#{ROLE_NAME} and IS_DEL='N' and cp_id=#{session_company_id} and role_id!=${ROLE_ID}" ></property>
	</validation>
    <!-- 删除角色时判断是否是固化角色 -->
    <validation id="delRole">
		<property field="ROLE_ID" method="database" msg="系统角色不允许删除" sql="select count(1) from cp_role_tab where ROLE_ID=${ROLE_ID} and IS_DEL='N' and cp_id=#{session_company_id} and role_type=1" ></property>
	</validation>
    <!-- 删除权限时判断是否还有子节点 -->
    <validation id="delPriv">
		<property field="id" method="database" msg="该权限下还有子权限,无法进行删除" sql="select count(1) from cp_priv_tab where pid=${id} and IS_DEL='N' and cp_id=#{session_company_id}" ></property>
	</validation>
	<!-- 保存角色时判断人员名是否存在 -->
    <validation id="addUser">
		<property field="USER_CODE" method="database" msg="用户名必须唯一" sql="select count(1) from cp_user_tab where IS_DEL='N' and CP_ID=#{session_company_id} and USER_CODE=#{USER_CODE}" ></property>
	</validation>
    <!-- 编辑角色时判断人员名是否存在 -->
    <validation id="editUser">
		<property field="USER_CODE" method="database" msg="用户名已存在" sql="select count(1) from cp_user_tab where USER_CODE=#{USER_CODE} and IS_DEL='N' and CP_ID=#{session_company_id} and USER_ID!=#{USER_ID}" ></property>
	</validation>
	<!-- 删除角色时判断人员名是否为系统管理员 -->
    <validation id="delUser">
		<property field="USER_CODE" method="database" msg="系统管理员不允许删除" sql="select count(1) from cp_user_tab where USER_ID=#{USER_ID} and IS_DEL='N' and CP_ID=#{session_company_id} and USER_CODE='admin'" ></property>
	</validation>
	<!-- 失效时判断人员名是否为系统管理员 -->
    <validation id="invalidUser">
		<property field="USER_CODE" method="database" msg="系统管理员不允许失效" sql="select count(1) from cp_user_tab where USER_ID=#{USER_ID} and IS_DEL='N' and CP_ID=#{session_company_id} and USER_CODE='admin'" ></property>
	</validation>
	<!--  -->
	<validation id="validatePwd">
	    <property field="validatePwd" method="database" msg="输入的旧密码错误" sql="select count(1) from ms_user_tab where USER_ID='$_CRU_USER_ID_$' AND USER_PWD!=md5(#{oldpwd}) "></property>
	</validation>
</validations>
